const quizData = [
    { question: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Rome"], answer: "Paris" },
    { question: "Who developed the theory of relativity?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Stephen Hawking"], answer: "Albert Einstein" },
    { question: "Which planet is known as the Red Planet?", options: ["Mars", "Jupiter", "Saturn", "Venus"], answer: "Mars" },
    { question: "Who painted the Mona Lisa?", options: ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Michelangelo"], answer: "Leonardo da Vinci" },
    { question: "What is the largest ocean on Earth?", options: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], answer: "Pacific Ocean" },
    { question: "Who wrote 'To Kill a Mockingbird'?", options: ["Harper Lee", "J.K. Rowling", "Mark Twain", "George Orwell"], answer: "Harper Lee" },
    { question: "What is the hardest natural substance on Earth?", options: ["Diamond", "Quartz", "Gold", "Ruby"], answer: "Diamond" },
    { question: "Which country is known as the Land of the Rising Sun?", options: ["Japan", "China", "South Korea", "Vietnam"], answer: "Japan" },
    { question: "What is the chemical symbol for water?", options: ["H2O", "CO2", "O2", "NaCl"], answer: "H2O" },
    { question: "Who was the first person to step on the Moon?", options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Alan Shepard"], answer: "Neil Armstrong" },
    { question: "Who is the author of '1984'?", options: ["George Orwell", "Ernest Hemingway", "F. Scott Fitzgerald", "J.R.R. Tolkien"], answer: "George Orwell" },
    { question: "What is the smallest planet in our solar system?", options: ["Mercury", "Mars", "Venus", "Earth"], answer: "Mercury" },
    { question: "Which organ produces insulin in the human body?", options: ["Pancreas", "Liver", "Kidney", "Heart"], answer: "Pancreas" },
    { question: "What is the largest land mammal?", options: ["Elephant", "Giraffe", "Hippopotamus", "Rhinoceros"], answer: "Elephant" },
    { question: "Who discovered penicillin?", options: ["Alexander Fleming", "Marie Curie", "Louis Pasteur", "Gregor Mendel"], answer: "Alexander Fleming" },
    { question: "What is the capital of Japan?", options: ["Tokyo", "Seoul", "Beijing", "Bangkok"], answer: "Tokyo" },
    { question: "Who painted the ceiling of the Sistine Chapel?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], answer: "Michelangelo" },
    { question: "Which planet is known as the Earth's Twin?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answer: "Venus" },
    { question: "What is the main ingredient in guacamole?", options: ["Avocado", "Tomato", "Onion", "Pepper"], answer: "Avocado" },
    { question: "Who wrote 'Pride and Prejudice'?", options: ["Jane Austen", "Charlotte Bronte", "Emily Bronte", "Mary Shelley"], answer: "Jane Austen" },
    { question: "What is the largest desert in the world?", options: ["Sahara Desert", "Arabian Desert", "Gobi Desert", "Kalahari Desert"], answer: "Sahara Desert" },
    { question: "Which element has the chemical symbol 'O'?", options: ["Oxygen", "Gold", "Osmium", "Oganesson"], answer: "Oxygen" },
    { question: "Who was the first President of the United States?", options: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], answer: "George Washington" },
    { question: "Which planet is known for its rings?", options: ["Saturn", "Jupiter", "Uranus", "Neptune"], answer: "Saturn" },
    { question: "What is the largest continent on Earth?", options: ["Asia", "Africa", "North America", "Europe"], answer: "Asia" },
    { question: "Who is known as the Father of Computer Science?", options: ["Alan Turing", "Bill Gates", "Steve Jobs", "Charles Babbage"], answer: "Charles Babbage" },
    { question: "What is the main ingredient in a traditional paella?", options: ["Rice", "Pasta", "Bread", "Potatoes"], answer: "Rice" },
    { question: "What is the tallest mountain in the world?", options: ["Mount Everest", "K2", "Kangchenjunga", "Lhotse"], answer: "Mount Everest" },
    { question: "Which gas do plants absorb from the atmosphere?", options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"], answer: "Carbon Dioxide" },
    { question: "Who wrote 'The Great Gatsby'?", options: ["F. Scott Fitzgerald", "Ernest Hemingway", "Mark Twain", "William Faulkner"], answer: "F. Scott Fitzgerald" }
];

export default quizData;
